logo: SCIE4701_icon.png
theme: jekyll-theme-cayman
title: SURGE Discover R
description: Coding workshop series develoepd by SURGE, Faculty of Science, Dalhousie University.
# Google Analytics
google_analytics: